services:
  dwpostgres:
    image: postgres:17rc1-alpine3.19
    container_name: dwpronto_postgres
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "5434:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - network_dw_prontocardio

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - "8081:8080"
    environment:
      - _PIP_ADDITIONAL_REQUIREMENTS=oracledb==1.1.0
      - POSTGRES_HOST=dwpostgres
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./dbt_dw_entradas:/usr/local/airflow/dbt
      - ./script_ingestao:/usr/local/airflow/script_ingestao
      - ./.dlt:/usr/local/airflow/.dlt
    depends_on:
      - dwpostgres
    networks:
      - network_dw_prontocardio
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./script_ingestao:/usr/local/airflow/script_ingestao
      - ./.dlt:/usr/local/airflow/.dlt
      - ./dbt_dw_entradas:/usr/local/airflow/dbt
    depends_on:
      - dwpostgres
    networks:
      - network_dw_prontocardio

  triggerer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./script_ingestao:/usr/local/airflow/script_ingestao
      - ./.dlt:/usr/local/airflow/.dlt
      - ./dbt_dw_entradas:/usr/local/airflow/dbt
    depends_on:
      - dwpostgres
    networks:
      - network_dw_prontocardio

volumes:
  postgres-volume:

networks:
  network_dw_prontocardio:
    name: network_dw_prontocardio
    driver: bridge
    external: false